# Generated by Django 4.0 on 2021-12-19 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articletags',
            old_name='main',
            new_name='is_main',
        ),
    ]
